version: '3'
services:
  server:
    build: 
      context: ./server
      args: 
        NODE_ENV: production
    environment:
     - NODE_ENV=production

  client:
    build: 
      context: ./server
      args: 
        NODE_ENV: production
    environment:
     - NODE_ENV=production
