version: '3'
services:
  server:
    build: 
      context: ./server
      args: 
        NODE_ENV: development


  client:
    build: 
      context: ./server
      args: 
        NODE_ENV: development
